app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include('webapp.urls')),
    path("auth/", include('accounts.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.base import IndexView, IndexRedirectView
from webapp.views.products import (
    ProductCreateView,
    ProductDetail,
    ProductUpdateView,
    ProductDeleteView,
)
from webapp.views.review_views import (
    ProductReviewCreateView,
    ReviewDetailView,
    ReviewUpdateView,
    ReviewDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "product/", IndexRedirectView.as_view(), name="products_index_redirect"
    ),
    path("product/add", ProductCreateView.as_view(), name="product_add"),
    path("product/<int:pk>", ProductDetail.as_view(), name="product_detail"),
    path(
        "product/<int:pk>/update/",
        ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="product_delete",
    ),
    path(
        "product/<int:pk>/confirm_delete/",
        ProductDeleteView.as_view(),
        name="confirm_delete",
    ),
    path(
        "product/<int:pk>/reviews/add/",
        ProductReviewCreateView.as_view(),
        name="product_review_add",
    ),
    path("review/<int:pk>", ReviewDetailView.as_view(), name="review_detail"),
    path(
        "review/<int:pk>/update/",
        ReviewUpdateView.as_view(),
        name="review_update",
    ),
    path(
        "review/<int:pk>/delete/",
        ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    path(
        "review/<int:pk>/delete/",
        ReviewDeleteView.as_view(),
        name="confirm_review_delete",
    ),
]

webapp/models/product.py
from django.db import models
from django.db.models import TextChoices
from django.utils import timezone
from django.core.validators import MinValueValidator


# Create your models here.


class StatusChoice(TextChoices):
    OTHER = "other", "Разное"
    PHONE = "phones", "Смартфоны"
    LAPTOP = "laptops", "Ноутбуки"


class Product(models.Model):
    title = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Название",
    )
    category = models.CharField(
        max_length=100,
        verbose_name="Категория",
        null=False,
        blank=False,
        choices=StatusChoice.choices,
        default=StatusChoice.OTHER,
    )
    description = models.TextField(
        max_length=2000, null=True, blank=True, verbose_name="Описание"
    )
    image = models.TextField(
        max_length=500,
        null=True,
        blank=True,
        verbose_name="Ссылка на изображение",
        default="https://texterra.ru/upload/iblock/17a/zk4qwtfo4ttmm4qrgtkne62ncyc70vyj/anons.webp",
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Время создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )
    is_deleted = models.BooleanField(
        verbose_name="удалено", null=False, default=False
    )

    def __str__(self):
        return f"{self.title} - {self.category} - {self.description} - {self.image}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

webapp/models/reviews.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import IntegerChoices


class RatingChoice(IntegerChoices):
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5


class Review(models.Model):
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_DEFAULT,
        max_length=30,
        default=1,
        related_name="reviews",
        verbose_name="Автор",
    )
    product = models.ForeignKey(
        "webapp.Product",
        related_name="reviews",
        on_delete=models.CASCADE,
        verbose_name="Продукт",
    )
    text = models.TextField(
        max_length=2000, verbose_name="Текст", null=False, blank=False
    )
    rating = models.IntegerField(
        verbose_name="Рейтинг",
        null=False,
        blank=False,
        choices=RatingChoice.choices,
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Время создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )

    def __str__(self):
        return f"{self.author} - {self.product} - {self.text[:25]} - {self.rating}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "title",
            "category",
            "description",
            "image",
        )

        labels = {
            "title": "Название",
            "category": "Категория",
            "description": "Описание",
            "image": "ссылка на изображение",
        }

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) < 2:
            raise ValidationError("Заголоаок должен быть длиннее 2 символов")
        if Product.objects.filter(title=title).exists():
            raise ValidationError("Заголовок с таким именем уже есть")
        return title


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = (
            "text",
            "rating",
        )

webapp/views/base.py
from django.views.generic import RedirectView, ListView

from webapp.models import Product


class IndexView(ListView):
    template_name = "index.html"
    model = Product
    context_object_name = "products"
    ordering = ("-created_at",)
    paginate_by = 2
    paginate_orphans = 1


class IndexRedirectView(RedirectView):
    pattern_name = "index"

webapp/views/products.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class GroupPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name__in=['Moderators', 'users']).exists()


class ProductCreateView(GroupPermissionMixin, SuccessMessageMixin, CreateView):
    template_name = "product_create.html"
    model = Product
    form_class = ProductForm
    success_message = "Продукт добавлен"
    groups = ['Moderators']

    def get_success_url(self):
        return reverse("product_detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProductUpdateView(GroupPermissionMixin, SuccessMessageMixin, UpdateView):
    template_name = "product_update.html"
    form_class = ProductForm
    model = Product
    success_message = "Продукт обновлен"
    groups = ['Moderators']

    def get_success_url(self):
        return reverse("product_detail", kwargs={"pk": self.object.pk})


class ProductDetail(DetailView):
    template_name = "product.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews = product.reviews.order_by("-created_at")
        context["reviews"] = reviews
        return context


class ProductDeleteView(GroupPermissionMixin, SuccessMessageMixin, DeleteView):
    template_name = "product_confirm_delete.html"
    model = Product
    success_url = reverse_lazy("index")
    success_message = "Продукт удален"
    groups = ['Moderators']

webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from webapp.forms import ProductReviewForm
from webapp.models import Product, Review
from webapp.views.products import GroupPermissionMixin


class ReviewDetailView(DetailView):
    template_name = "review.html"
    model = Review


class ProductReviewCreateView(GroupPermissionMixin, PermissionRequiredMixin, CreateView):
    model = Review
    template_name = "review_create.html"
    form_class = ProductReviewForm
    groups = ['users']

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        review = form.save(commit=False)
        review.product = product
        review.author = self.request.user
        review.save()
        return redirect("product_detail", pk=product.pk)

    def test_func(self):
        return self.get_object().author == self.request.user or \
            self.request.user.has_perm('add_review')


class ReviewUpdateView(GroupPermissionMixin, PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = "review_update.html"
    form_class = ProductReviewForm
    context_object_name = "review"
    groups = ['Moderators']

    def get_success_url(self):
        return reverse("review_detail", kwargs={"pk": self.object.pk})

    def test_func(self):
        return self.get_object().author == self.request.user or \
            self.request.user.has_perm('change_review')


class ReviewDeleteView(GroupPermissionMixin, PermissionRequiredMixin, DeleteView):
    template_name = "review_confirm_delete.html"
    model = Review
    success_url = reverse_lazy("index")
    groups = ['Moderators']

    def test_func(self):
        return self.get_object().author == self.request.user or \
            self.request.user.has_perm('delete_review')

webapp/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <title>{% block title %}Review{% endblock %}</title>
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container d-flex">
                <a class="navbar-brand p-2 flex-fill" href="/"><img src="../../static/img/logo.png" alt="Home"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'index' %}">Home</a>
                        </li>
                        {% block menu %}{% endblock %}
                        {% if request.user.is_authenticated %}
                        {% if perms.webapp.add_product %}
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'product_add' %}">Add Product</a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'profile' user.pk %}" class="btn btn-primary">Profile</a>
                        </li>
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-primary" value="Выйти">
                            </form>
                        </li>
                        <l class="btn"><b>Привет {{ user.username }}</b></l>
                            {% else %}
                        <li>
                              <a href="{% url 'login' %}?next={{ request.get_full_path }}" class="btn btn-primary">Sign in</a>
                              <a href="{% url 'register' %}" class="btn btn-primary">Sign Up</a>
                        </li>
                            {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-8 footer-block">
                    <h5 class="footer-title">Contact Us</h5>
                    <p class="footer-text">+ 7 775 959 66 71</p>
                </div>
                <div class="col-4 footer-block">
                    <h5 class="footer-title">Lorem, ipsum dolor.</h5>
                    <p class="footer-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro consequatur
                        totam fuga.
                        quod.</p>
                </div>
            </div>
            <div class="copyright">
                <p class="copyright-text">Copyright 2023</p>
            </div>
        </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for product in products %}
        <div class="col">
            <ol class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <img class="image_flex_products" src="{{ product.image }}" alt="product photo">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'product_detail' product.pk%}">Title: {{ product.title }}</a>
                        </div>
                        <div class="fw-bold">Categories: {{ product.category }}</div>
                        <span class="badge bg-info rounded-pill">
                            <a href="{% url 'product_detail' product.pk%}" class="button-text-color">see more
                                >>></a></span>
                    </div>
                </li>
            </ol>
        </div>
        {% empty %}
        <h3>Records not found</h3>
        {% endfor %}
    </div>
    {% if is_paginated %}
    {% include 'partial/pagination.html' %}
    {% endif %}
</div>
{% endblock %}

webapp/templates/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock %}
{% block menu %}
{% if user.is_authenticated %}
{% if perms.webapp.change_product %}
<a href="{% url 'product_update' product.pk %}" class="btn btn-success">Update Product</a>
{% endif %}
{% if perms.webapp.delete_product %}
<a href="{% url 'product_delete' product.pk %}" class="btn btn-danger">Delete Product</a>
{% endif %}
{% if perms.webapp.add_review %}
<a href="{% url 'product_review_add' product.pk %}" class="btn btn-primary">Add review</a></li>
{% endif %}
{% endif %}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="card mb-3 modern">
        <div class="row g-0">
            <div class="col-md-6">
                <img class="image_flex_product" src="{{ product.image }}" alt="product photo">
            </div>
            <div class="col-12 col-sm-12 col-lg-6">
                <div class="card-body">
                    <h1 class="card-title">Title: {{ product.title }}</h1>
                    <p>Category: {{ product.category }}</p>
                    <p class="card-text transfer_text_space">Description: {{ product.description }}</p>
                    {% for rating in product.reviews.all %}
                    <p>Rating: {{ rating.rating }}</p>
                    {% endfor %}
                    <h4>Reviews:</h4>

                    {% for review in reviews %}
                    <div>
                        <p><b>Review author: {{ review.author }}</b> placed at {{ review.created_at|date:'d.m.Y H:i:s'
                            }}</p>
                        <div class="pre"><b>Review text:</b> {{ review.text }}</div>
                        <div class="pre"><b>Product's rating:</b> {{ review.rating }}</div>
                    </div>
                    <p>
                        <a href="{% url 'review_detail' review.pk %}">See more..</a>
                    </p>
                    {% empty %}
                    <p>No reviews yet.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

webapp/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Product confirm delete{% endblock %}
{% block menu %}

{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1>Are you sure you want to delete the product?</h1>
    <div class="card mb-3 modern">
        <div class="row g-0">
            <div class="col-md-6">
                <img class="image_flex_product" src="{{ product.image }}" alt="product photo">
            </div>
            <div class="col-12 col-sm-12 col-lg-6">
                <div class="card-body">
                    <h1 class="card-title">{{ product.title }}</h1>
           А         <p>{{ product.category }}</p>
                    <p class="card-text transfer_text_space">{{ product.description }}</p>
                    <form action="{% url 'confirm_delete' product.pk %}" method="post">
                {% csrf_token %}
                <span><input class="btn btn-danger" type="submit" value="Delete"></span>
                        <span><a class="btn btn-info" href="{% url 'index' %}">Cancel</a></span>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/product_create.html
{% extends 'base.html' %}
{% block title %}Product Create{% endblock %}
{% block content %}
<h1>New Product</h1>
<div class="container">
    <div class="form">
        <form action="{% url 'product_add' %}" method="post">
            {% include 'partial/product_form.html' with button_text='Create' %}
        </form>
    </div>
</div>
{% endblock %}

webapp/templates/product_update.html
{% extends 'base.html' %}
{% block title %}Product Update{% endblock %}
{% block content %}
<h1>Product update</h1>
<div class="container">
    <div class="form">
        <form action="{% url 'product_update' product.pk%}" method="post">
            {% include 'partial/product_form.html' with button_text='Update' %}
        </form>
    </div>
</div>
{% endblock %}

webapp/templates/review.html
{% extends 'base.html' %}
{% block title %}Review{% endblock %}
{% block menu %}
{% if user.is_authenticated %}
{% if perms.webapp.change_review or review.author == request.user%}
<a class="btn btn-success" href="{% url 'review_update' review.pk %}">Update review</a>
{% endif %}
{% if perms.webapp.delete_review or review.author == request.user%}
<a class="btn btn-danger" href="{% url 'review_delete' review.pk %}">Delete review</a>
{% endif %}
{% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <h1>Review</h1>
    <p>Author: {{ review.author }}</p>
    <p>Text: {{ review.text }}</p>
    <p>Rating: {{ review.rating }}</p>
</div>
{% endblock %}

webapp/templates/review_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Review confirm delete{% endblock %}
{% block menu %}

{% endblock %}
{% block content %}
<div class="container">
    <h1>Are you sure you want to delete the review?</h1>
    <p>Author: {{ review.author }}</p>
    <p>Text: {{ review.text }}</p>
    <p>Rating: {{ review.text }}</p>
    <form action="{% url 'confirm_review_delete' review.pk %}" method="post">
        {% csrf_token %}
        <p><input type="submit" value="Delete" class="btn btn-danger"></p>
        <p><a href="{% url 'index' %}" class="btn btn-primary">Cancel</a></p>
    </form>
</div>
{% endblock %}

webapp/templates/review_create.html
{% extends 'base.html' %}

{% block title %}Create review{% endblock %}

{% block content %}
<div class="container">
    <h2>Create review</h2>
    <div class="form">
        <form action="" method="post">
            {% include 'partial/product_form.html' with button_text='Create' %}
        </form>
    </div>
</div>

{% endblock %}

webapp/templates/review_update.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
<div class="container">
    <h2>Create review</h2>
    <div class="form">
        <form action="" method="post">
            {% include 'partial/product_form.html' with button_text='Update' %}
        </form>
    </div>
</div>

{% endblock %}